### ISSUE TITLE
How does this improve security?

### ISSUE THREAD

**Issue by Sequoia** [helmetjs/dns-prefetch-control#1]
Chrome & Firefox docs linked don't make clear how disabling pre-fetching improves security.

**Comment by EvanHahn** [comment]
It helps to improve the user's privacy.

For example, let's say I'm on example.com. It's reasonable to expect that example.com has a record that I was there—perhaps my IP address is in a log somewhere. But if the page I'm on has a link to github.com, I might not expect to have my IP address show up in one of GitHub's logs.

**Comment by Sequoia** [comment]
Makes sense!

**Comment by EvanHahn** [comment]
Let me know if you have any other questions/issues!
